

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev   # 👈 use dev version
    container_name: backend_dev
    env_file:
      - .env.dev
    volumes:
      - .:/app  # live code reload
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      sh -c "alembic upgrade head && 
            uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: postgres:15
    container_name: postgres_dev
    restart: always
    env_file:
      - .env.dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data_dev:
