

services:
  backend:
    build: .
    container_name: fastapi_app
    env_file:
      - .env.prod   # 👈 change this if running locally
    environment:
      - GUNICORN_CMD_ARGS=--bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - db
    command: >
      sh -c "alembic upgrade head && \
             gunicorn -k uvicorn.workers.UvicornWorker app.main:app \
             --workers 4 \
             --timeout 60"

  db:
    image: postgres:15
    container_name: fastapi_db
    env_file:
      - .env.prod   # will be ignored in prod if using Neon
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
